# -*- coding: utf-8 -*-
"""OCR_TARP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XRbzpi2vUENhSVMGpv9oVfm3vZ00-v7o
"""

!pip install pytesseract

from PIL import Image
import pytesseract
import numpy as np
import cv2
from google.colab.patches import cv2_imshow

filename = 'TARP1.jfif'
img1 = np.array(Image.open(filename))
cv2_imshow(img1)
text = pytesseract.image_to_string(img1)
print(text)

